-- =============================================================================
-- AirDesk — Phase 0 DRAFT database schema
-- Target: SQLite >= 3.45 (STRICT tables, FTS5 trigram), accessed from Node via
-- better-sqlite3 (SQLCipher-capable build). This file is a SPECIFICATION
-- artifact: Phase 1 turns it into numbered migrations (0001_*.sql ...).
--
-- Conventions (see 03-database-schema.md):
--   * Primary keys: TEXT ULIDs (26 chars), generated by the application.
--   * Money: INTEGER minor units ("*_minor"), never REAL. Every money column
--     is accompanied by a currency (explicit column or documented context).
--   * "*_base_minor": amount converted to the company base currency at posting
--     time and FROZEN. Never recomputed.
--   * Exchange rates: TEXT decimal strings (e.g. '50.4500'), parsed with a
--     decimal library. 1 unit of transaction currency = rate units of base.
--   * Instants: TEXT ISO-8601 UTC ('2026-09-28T11:14:00.000Z')  -> "*_at".
--   * Business dates: TEXT 'YYYY-MM-DD' in company timezone     -> "*_date".
--   * Airport-local flight times: TEXT 'HH:MM' + local date + airport code.
--   * Booleans: INTEGER 0/1 with CHECK.
--   * Posted financial rows are IMMUTABLE (enforced by triggers below).
-- =============================================================================

PRAGMA foreign_keys = ON;

-- -----------------------------------------------------------------------------
-- 0. Meta
-- -----------------------------------------------------------------------------
CREATE TABLE schema_migration (
  version      INTEGER PRIMARY KEY,
  name         TEXT NOT NULL,
  checksum     TEXT NOT NULL,              -- sha256 of the migration file
  applied_at   TEXT NOT NULL,
  app_version  TEXT NOT NULL
) STRICT;

CREATE TABLE installation (
  id               TEXT PRIMARY KEY,       -- ULID generated on first run
  created_at       TEXT NOT NULL,
  created_app_version TEXT NOT NULL
) STRICT;

-- -----------------------------------------------------------------------------
-- 1. Identity & access
-- -----------------------------------------------------------------------------
CREATE TABLE app_user (
  id                    TEXT PRIMARY KEY,
  username              TEXT NOT NULL UNIQUE COLLATE NOCASE,
  display_name          TEXT NOT NULL,
  password_hash         TEXT NOT NULL,     -- Argon2id PHC string. NEVER plaintext.
  must_change_password  INTEGER NOT NULL DEFAULT 1 CHECK (must_change_password IN (0,1)),
  is_active             INTEGER NOT NULL DEFAULT 1 CHECK (is_active IN (0,1)),
  failed_login_count    INTEGER NOT NULL DEFAULT 0 CHECK (failed_login_count >= 0),
  locked_until          TEXT,
  last_login_at         TEXT,
  password_changed_at   TEXT NOT NULL,
  preferred_locale      TEXT CHECK (preferred_locale IN ('ar','en')),
  created_at            TEXT NOT NULL,
  created_by            TEXT REFERENCES app_user(id),
  updated_at            TEXT NOT NULL,
  row_version           INTEGER NOT NULL DEFAULT 1
) STRICT;

CREATE TABLE role (
  id           TEXT PRIMARY KEY,
  code         TEXT NOT NULL UNIQUE,       -- ADMIN, MANAGER, ACCOUNTANT, SALES_AGENT, custom...
  name_ar      TEXT NOT NULL,
  name_en      TEXT NOT NULL,
  description  TEXT,
  is_system    INTEGER NOT NULL DEFAULT 0 CHECK (is_system IN (0,1)),
  created_at   TEXT NOT NULL,
  row_version  INTEGER NOT NULL DEFAULT 1
) STRICT;

-- Seeded from code on every migration run; the code is the source of truth.
CREATE TABLE permission (
  code          TEXT PRIMARY KEY,          -- e.g. 'booking.view_cost'
  module        TEXT NOT NULL,
  is_sensitive  INTEGER NOT NULL DEFAULT 0 CHECK (is_sensitive IN (0,1)),
  description_ar TEXT NOT NULL,
  description_en TEXT NOT NULL
) STRICT;

CREATE TABLE role_permission (
  role_id          TEXT NOT NULL REFERENCES role(id) ON DELETE CASCADE,
  permission_code  TEXT NOT NULL REFERENCES permission(code),
  PRIMARY KEY (role_id, permission_code)
) STRICT;

CREATE TABLE user_role (
  user_id  TEXT NOT NULL REFERENCES app_user(id),
  role_id  TEXT NOT NULL REFERENCES role(id),
  PRIMARY KEY (user_id, role_id)
) STRICT;

CREATE TABLE user_session (
  id                TEXT PRIMARY KEY,
  user_id           TEXT NOT NULL REFERENCES app_user(id),
  workstation_name  TEXT NOT NULL,
  started_at        TEXT NOT NULL,
  last_seen_at      TEXT NOT NULL,
  ended_at          TEXT,
  end_reason        TEXT CHECK (end_reason IN ('LOGOUT','IDLE_TIMEOUT','APP_EXIT','FORCED','CRASH_RECOVERY'))
) STRICT;

-- -----------------------------------------------------------------------------
-- 2. Company settings (white label) & reference data
-- -----------------------------------------------------------------------------
CREATE TABLE currency (
  code        TEXT PRIMARY KEY CHECK (length(code) = 3 AND code = upper(code)),
  name_ar     TEXT NOT NULL,
  name_en     TEXT NOT NULL,
  symbol      TEXT,
  minor_unit  INTEGER NOT NULL CHECK (minor_unit BETWEEN 0 AND 4),  -- EGP/SAR/USD/EUR = 2, KWD = 3
  is_active   INTEGER NOT NULL DEFAULT 1 CHECK (is_active IN (0,1))
) STRICT;

CREATE TABLE company_profile (
  id                          INTEGER PRIMARY KEY CHECK (id = 1),   -- singleton
  legal_name_ar               TEXT NOT NULL,
  legal_name_en               TEXT,
  trade_name_ar               TEXT,
  trade_name_en               TEXT,
  logo                        BLOB,
  logo_mime                   TEXT CHECK (logo_mime IN ('image/png','image/jpeg','image/svg+xml')),
  address_ar                  TEXT,
  address_en                  TEXT,
  phone_primary               TEXT,
  phone_secondary             TEXT,
  email                       TEXT,
  website                     TEXT,
  tax_registration_no         TEXT,
  commercial_registration_no  TEXT,
  iata_agency_code            TEXT,
  base_currency_code          TEXT NOT NULL REFERENCES currency(code),  -- frozen after first posting
  default_country_code        TEXT NOT NULL,        -- ISO-3166 alpha-2, phone normalisation
  timezone                    TEXT NOT NULL,        -- IANA, defines "today"
  default_locale              TEXT NOT NULL DEFAULT 'ar' CHECK (default_locale IN ('ar','en')),
  financial_lock_date         TEXT,                 -- no document may be dated <= this
  document_footer_ar          TEXT,
  document_footer_en          TEXT,
  updated_at                  TEXT NOT NULL,
  updated_by                  TEXT REFERENCES app_user(id),
  row_version                 INTEGER NOT NULL DEFAULT 1
) STRICT;

-- Typed-by-convention key/value settings validated by zod schemas in code.
-- e.g. 'aging.buckets' = [0,7,30,60], 'session.idle_minutes' = 15,
--      'schedule_change.major_threshold_minutes' = 60, 'backup.policy' = {...}
CREATE TABLE app_setting (
  key         TEXT PRIMARY KEY,
  value_json  TEXT NOT NULL CHECK (json_valid(value_json)),
  updated_at  TEXT NOT NULL,
  updated_by  TEXT REFERENCES app_user(id)
) STRICT;

-- Gap-free human numbers (BK-2026-000123, RCT-2026-000045 ...). Incremented
-- inside the same write transaction that creates the numbered row.
CREATE TABLE document_sequence (
  sequence_key  TEXT NOT NULL,            -- 'BOOKING', 'CUSTOMER_RECEIPT', ...
  period_key    TEXT NOT NULL,            -- '2026' for yearly reset, '' for none
  prefix        TEXT NOT NULL,
  next_value    INTEGER NOT NULL CHECK (next_value >= 1),
  PRIMARY KEY (sequence_key, period_key)
) STRICT;

CREATE TABLE exchange_rate (
  id             TEXT PRIMARY KEY,
  currency_code  TEXT NOT NULL REFERENCES currency(code),
  rate_date      TEXT NOT NULL,
  rate           TEXT NOT NULL,           -- decimal string, > 0
  source         TEXT NOT NULL DEFAULT 'MANUAL',
  created_at     TEXT NOT NULL,
  created_by     TEXT NOT NULL REFERENCES app_user(id),
  UNIQUE (currency_code, rate_date, source)
) STRICT;

CREATE TABLE airport (
  iata_code     TEXT PRIMARY KEY CHECK (length(iata_code) = 3),
  icao_code     TEXT,
  name_en       TEXT NOT NULL,
  name_ar       TEXT,
  city_en       TEXT,
  city_ar       TEXT,
  country_code  TEXT NOT NULL,
  timezone      TEXT,                     -- IANA; NULL => UTC derivation impossible
  is_active     INTEGER NOT NULL DEFAULT 1 CHECK (is_active IN (0,1))
) STRICT;

CREATE TABLE airline (
  id              TEXT PRIMARY KEY,
  iata_code       TEXT,                   -- 'MS'
  icao_code       TEXT,                   -- 'MSR'
  ticket_prefix   TEXT,                   -- 3-digit accounting code, '077'
  name_en         TEXT NOT NULL,
  name_ar         TEXT,
  phone           TEXT,
  email           TEXT,
  website         TEXT,
  notes           TEXT,
  is_active       INTEGER NOT NULL DEFAULT 1 CHECK (is_active IN (0,1)),
  created_at      TEXT NOT NULL,
  created_by      TEXT REFERENCES app_user(id),
  updated_at      TEXT NOT NULL,
  row_version     INTEGER NOT NULL DEFAULT 1
) STRICT;
CREATE UNIQUE INDEX ux_airline_iata ON airline(iata_code) WHERE iata_code IS NOT NULL AND is_active = 1;

-- -----------------------------------------------------------------------------
-- 3. Parties
-- -----------------------------------------------------------------------------
CREATE TABLE customer (
  id                   TEXT PRIMARY KEY,
  customer_no          TEXT NOT NULL UNIQUE,
  customer_type        TEXT NOT NULL DEFAULT 'INDIVIDUAL' CHECK (customer_type IN ('INDIVIDUAL','CORPORATE')),
  full_name            TEXT NOT NULL,
  full_name_latin      TEXT,
  primary_mobile       TEXT NOT NULL,     -- E.164 normalised, '+201001234567'
  primary_mobile_raw   TEXT NOT NULL,     -- as typed
  secondary_mobile     TEXT,
  whatsapp_number      TEXT,
  email                TEXT,
  national_id          TEXT,              -- sensitive (customer.view_identity)
  passport_no          TEXT,              -- sensitive
  passport_expiry      TEXT,
  nationality          TEXT,
  date_of_birth        TEXT,
  preferred_locale     TEXT CHECK (preferred_locale IN ('ar','en')),
  preferred_channel    TEXT CHECK (preferred_channel IN ('WHATSAPP','SMS','EMAIL','PHONE_CALL')),
  payment_terms_days   INTEGER NOT NULL DEFAULT 0 CHECK (payment_terms_days >= 0),
  credit_limit_minor   INTEGER CHECK (credit_limit_minor >= 0),  -- base currency; NULL = none
  notes                TEXT,
  is_active            INTEGER NOT NULL DEFAULT 1 CHECK (is_active IN (0,1)),
  created_at           TEXT NOT NULL,
  created_by           TEXT NOT NULL REFERENCES app_user(id),
  updated_at           TEXT NOT NULL,
  updated_by           TEXT REFERENCES app_user(id),
  row_version          INTEGER NOT NULL DEFAULT 1
) STRICT;
CREATE INDEX ix_customer_mobile ON customer(primary_mobile);   -- NOT unique: families share phones

-- Saved traveller profiles (a customer may book for many travellers).
CREATE TABLE traveler (
  id               TEXT PRIMARY KEY,
  customer_id      TEXT REFERENCES customer(id),
  title            TEXT,
  given_name       TEXT NOT NULL,          -- Latin, as on passport
  surname          TEXT NOT NULL,
  name_ar          TEXT,
  gender           TEXT CHECK (gender IN ('M','F','X')),
  date_of_birth    TEXT,
  passport_no      TEXT,
  passport_expiry  TEXT,
  nationality      TEXT,
  mobile           TEXT,
  created_at       TEXT NOT NULL,
  updated_at       TEXT NOT NULL,
  row_version      INTEGER NOT NULL DEFAULT 1
) STRICT;

CREATE TABLE supplier (
  id                     TEXT PRIMARY KEY,
  supplier_no            TEXT NOT NULL UNIQUE,
  name                   TEXT NOT NULL,
  contact_person         TEXT,
  phone                  TEXT,
  email                  TEXT,
  address                TEXT,
  airline_id             TEXT REFERENCES airline(id),  -- set ONLY when the supplier IS an airline
  default_currency_code  TEXT NOT NULL REFERENCES currency(code),
  payment_terms_days     INTEGER NOT NULL DEFAULT 0 CHECK (payment_terms_days >= 0),
  notes                  TEXT,
  is_active              INTEGER NOT NULL DEFAULT 1 CHECK (is_active IN (0,1)),
  created_at             TEXT NOT NULL,
  created_by             TEXT NOT NULL REFERENCES app_user(id),
  updated_at             TEXT NOT NULL,
  updated_by             TEXT REFERENCES app_user(id),
  row_version            INTEGER NOT NULL DEFAULT 1
) STRICT;

-- Where money physically sits: cash drawer, bank account, wallet (InstaPay, Vodafone Cash), card clearing.
CREATE TABLE money_account (
  id             TEXT PRIMARY KEY,
  name           TEXT NOT NULL UNIQUE,
  account_type   TEXT NOT NULL CHECK (account_type IN ('CASH','BANK','WALLET','CARD_CLEARING')),
  currency_code  TEXT NOT NULL REFERENCES currency(code),
  bank_name      TEXT,
  account_ref    TEXT,
  is_active      INTEGER NOT NULL DEFAULT 1 CHECK (is_active IN (0,1)),
  created_at     TEXT NOT NULL,
  created_by     TEXT NOT NULL REFERENCES app_user(id),
  row_version    INTEGER NOT NULL DEFAULT 1
) STRICT;

-- -----------------------------------------------------------------------------
-- 4. Chart of accounts (system-seeded, small, users never see debits/credits)
-- -----------------------------------------------------------------------------
CREATE TABLE ledger_account (
  code           TEXT PRIMARY KEY,
  name_ar        TEXT NOT NULL,
  name_en        TEXT NOT NULL,
  account_class  TEXT NOT NULL CHECK (account_class IN
                   ('ASSET','LIABILITY','EQUITY','REVENUE','CONTRA_REVENUE',
                    'COST','CONTRA_COST','EXPENSE','OTHER')),
  normal_side    TEXT NOT NULL CHECK (normal_side IN ('DEBIT','CREDIT')),
  dimension      TEXT NOT NULL DEFAULT 'NONE'
                   CHECK (dimension IN ('NONE','CUSTOMER','SUPPLIER','MONEY_ACCOUNT')),
  is_system      INTEGER NOT NULL DEFAULT 1 CHECK (is_system IN (0,1)),
  is_active      INTEGER NOT NULL DEFAULT 1 CHECK (is_active IN (0,1))
) STRICT;

CREATE TABLE expense_category (
  id                   TEXT PRIMARY KEY,
  code                 TEXT NOT NULL UNIQUE,
  name_ar              TEXT NOT NULL,
  name_en              TEXT NOT NULL,
  ledger_account_code  TEXT NOT NULL REFERENCES ledger_account(code),
  is_active            INTEGER NOT NULL DEFAULT 1 CHECK (is_active IN (0,1))
) STRICT;

-- -----------------------------------------------------------------------------
-- 5. Bookings, passengers, segments, tickets
-- -----------------------------------------------------------------------------
CREATE TABLE booking (
  id                     TEXT PRIMARY KEY,
  booking_no             TEXT NOT NULL UNIQUE,            -- BK-2026-000123
  customer_id            TEXT NOT NULL REFERENCES customer(id),
  status                 TEXT NOT NULL DEFAULT 'DRAFT' CHECK (status IN
                           ('DRAFT','RESERVED','ISSUED','PARTIALLY_CANCELLED','CANCELLED','VOIDED','DISCARDED')),
  booking_date           TEXT NOT NULL,
  issue_date             TEXT,                            -- set on ISSUED; drives revenue date
  due_date               TEXT,                            -- issue_date + customer terms; drives aging
  ticketing_deadline_at  TEXT,                            -- for RESERVED holds
  primary_pnr            TEXT,
  trip_type              TEXT CHECK (trip_type IN ('ONE_WAY','ROUND_TRIP','MULTI_CITY')),
  default_supplier_id    TEXT REFERENCES supplier(id),
  sale_currency_code     TEXT NOT NULL REFERENCES currency(code),
  contact_name           TEXT NOT NULL,                   -- snapshot for notifications
  contact_mobile         TEXT NOT NULL,                   -- E.164 snapshot
  contact_whatsapp       TEXT,
  contact_email          TEXT,
  sales_agent_id         TEXT NOT NULL REFERENCES app_user(id),
  notes                  TEXT,
  created_at             TEXT NOT NULL,
  created_by             TEXT NOT NULL REFERENCES app_user(id),
  updated_at             TEXT NOT NULL,
  updated_by             TEXT REFERENCES app_user(id),
  row_version            INTEGER NOT NULL DEFAULT 1,
  CHECK (status NOT IN ('ISSUED','PARTIALLY_CANCELLED','CANCELLED','VOIDED') OR issue_date IS NOT NULL)
) STRICT;
CREATE INDEX ix_booking_customer ON booking(customer_id);
CREATE INDEX ix_booking_status_date ON booking(status, issue_date);
CREATE INDEX ix_booking_pnr ON booking(primary_pnr);

CREATE TABLE booking_status_history (
  id           TEXT PRIMARY KEY,
  booking_id   TEXT NOT NULL REFERENCES booking(id),
  from_status  TEXT,
  to_status    TEXT NOT NULL,
  changed_at   TEXT NOT NULL,
  changed_by   TEXT NOT NULL REFERENCES app_user(id),
  reason       TEXT
) STRICT;
CREATE INDEX ix_booking_status_history ON booking_status_history(booking_id, changed_at);

CREATE TABLE booking_passenger (
  id               TEXT PRIMARY KEY,
  booking_id       TEXT NOT NULL REFERENCES booking(id),
  seq              INTEGER NOT NULL CHECK (seq >= 1),
  traveler_id      TEXT REFERENCES traveler(id),
  pax_type         TEXT NOT NULL DEFAULT 'ADT' CHECK (pax_type IN ('ADT','CHD','INF')),
  title            TEXT,
  given_name       TEXT NOT NULL,
  surname          TEXT NOT NULL,
  name_ar          TEXT,
  gender           TEXT CHECK (gender IN ('M','F','X')),
  date_of_birth    TEXT,
  passport_no      TEXT,
  passport_expiry  TEXT,
  nationality      TEXT,
  mobile           TEXT,
  status           TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','CANCELLED')),
  row_version      INTEGER NOT NULL DEFAULT 1,
  UNIQUE (booking_id, seq)
) STRICT;

CREATE TABLE flight_segment (
  id                     TEXT PRIMARY KEY,
  booking_id             TEXT NOT NULL REFERENCES booking(id),
  seq                    INTEGER NOT NULL CHECK (seq >= 1),
  marketing_airline_id   TEXT NOT NULL REFERENCES airline(id),
  operating_airline_id   TEXT REFERENCES airline(id),
  flight_number          TEXT NOT NULL,
  origin_iata            TEXT NOT NULL REFERENCES airport(iata_code),
  destination_iata       TEXT NOT NULL REFERENCES airport(iata_code),
  departure_date         TEXT NOT NULL,                 -- airport-local
  departure_time         TEXT NOT NULL,                 -- 'HH:MM' airport-local
  arrival_date           TEXT NOT NULL,
  arrival_time           TEXT NOT NULL,
  departure_utc          TEXT,                          -- derived if airport tz known
  arrival_utc            TEXT,
  departure_terminal     TEXT,
  arrival_terminal       TEXT,
  cabin_class            TEXT NOT NULL CHECK (cabin_class IN ('ECONOMY','PREMIUM_ECONOMY','BUSINESS','FIRST')),
  booking_class          TEXT,                          -- RBD letter
  airline_locator        TEXT,                          -- airline-side PNR if different
  status                 TEXT NOT NULL DEFAULT 'CONFIRMED' CHECK (status IN ('CONFIRMED','WAITLISTED','CANCELLED')),
  version                INTEGER NOT NULL DEFAULT 1,    -- bumps on every schedule change
  created_at             TEXT NOT NULL,
  updated_at             TEXT NOT NULL,
  row_version            INTEGER NOT NULL DEFAULT 1,
  UNIQUE (booking_id, seq),
  CHECK (origin_iata <> destination_iata),
  CHECK (arrival_date >= departure_date)
) STRICT;
CREATE INDEX ix_segment_departure ON flight_segment(departure_date, departure_time);

CREATE TABLE ticket (
  id                        TEXT PRIMARY KEY,
  booking_id                TEXT NOT NULL REFERENCES booking(id),
  passenger_id              TEXT NOT NULL REFERENCES booking_passenger(id),
  ticket_number             TEXT,                      -- 13 digits; may be filled after issue
  validating_airline_id     TEXT REFERENCES airline(id),
  supplier_id               TEXT NOT NULL REFERENCES supplier(id),   -- current supplier
  status                    TEXT NOT NULL DEFAULT 'ISSUED' CHECK (status IN
                              ('ISSUED','VOIDED','EXCHANGED','REFUNDED','PARTIALLY_REFUNDED','USED')),
  issue_date                TEXT NOT NULL,
  exchanged_from_ticket_id  TEXT REFERENCES ticket(id),
  created_at                TEXT NOT NULL,
  updated_at                TEXT NOT NULL,
  row_version               INTEGER NOT NULL DEFAULT 1
) STRICT;
CREATE UNIQUE INDEX ux_ticket_number ON ticket(ticket_number) WHERE ticket_number IS NOT NULL;
CREATE INDEX ix_ticket_booking ON ticket(booking_id);
CREATE INDEX ix_ticket_supplier ON ticket(supplier_id);

CREATE TABLE ticket_segment (         -- which coupons a ticket covers
  ticket_id   TEXT NOT NULL REFERENCES ticket(id),
  segment_id  TEXT NOT NULL REFERENCES flight_segment(id),
  PRIMARY KEY (ticket_id, segment_id)
) STRICT;

-- -----------------------------------------------------------------------------
-- 6. Cancellation / refund workflow (non-financial state; money moves only via fin_document)
-- -----------------------------------------------------------------------------
CREATE TABLE cancellation_request (
  id                              TEXT PRIMARY KEY,
  request_no                      TEXT NOT NULL UNIQUE,
  booking_id                      TEXT NOT NULL REFERENCES booking(id),
  cancel_type                     TEXT NOT NULL CHECK (cancel_type IN ('VOID','REFUND','NON_REFUNDABLE')),
  scope                           TEXT NOT NULL CHECK (scope IN ('FULL','PARTIAL')),
  overall_status                  TEXT NOT NULL DEFAULT 'OPEN' CHECK (overall_status IN ('OPEN','CLOSED','WITHDRAWN')),
  supplier_status                 TEXT NOT NULL DEFAULT 'PENDING' CHECK (supplier_status IN
                                    ('PENDING','SUBMITTED','CONFIRMED','REJECTED','NOT_APPLICABLE')),
  customer_status                 TEXT NOT NULL DEFAULT 'PENDING' CHECK (customer_status IN
                                    ('PENDING','CREDITED','NOT_APPLICABLE')),
  expected_supplier_refund_minor  INTEGER CHECK (expected_supplier_refund_minor >= 0),  -- memo only, never posted
  expected_currency_code          TEXT REFERENCES currency(code),
  reason                          TEXT NOT NULL,
  requested_at                    TEXT NOT NULL,
  requested_by                    TEXT NOT NULL REFERENCES app_user(id),
  closed_at                       TEXT,
  notes                           TEXT,
  row_version                     INTEGER NOT NULL DEFAULT 1
) STRICT;

CREATE TABLE cancellation_item (
  id                       TEXT PRIMARY KEY,
  cancellation_request_id  TEXT NOT NULL REFERENCES cancellation_request(id),
  passenger_id             TEXT REFERENCES booking_passenger(id),
  segment_id               TEXT REFERENCES flight_segment(id),
  ticket_id                TEXT REFERENCES ticket(id),
  CHECK (passenger_id IS NOT NULL OR segment_id IS NOT NULL OR ticket_id IS NOT NULL)
) STRICT;

-- -----------------------------------------------------------------------------
-- 7. Financial documents (immutable once inserted) and the journal
-- -----------------------------------------------------------------------------
CREATE TABLE fin_document (
  id                       TEXT PRIMARY KEY,
  doc_type                 TEXT NOT NULL CHECK (doc_type IN (
                             'CUSTOMER_INVOICE','CUSTOMER_CREDIT_NOTE','CUSTOMER_RECEIPT','CUSTOMER_REFUND',
                             'SUPPLIER_BILL','SUPPLIER_CREDIT_NOTE','SUPPLIER_PAYMENT','SUPPLIER_REFUND',
                             'EXPENSE','MONEY_TRANSFER','BALANCE_APPLICATION','OPENING_BALANCE','FX_ADJUSTMENT')),
  doc_no                   TEXT NOT NULL UNIQUE,
  doc_date                 TEXT NOT NULL,             -- accounting date (period)
  is_reversal              INTEGER NOT NULL DEFAULT 0 CHECK (is_reversal IN (0,1)),
  reversal_of_id           TEXT UNIQUE REFERENCES fin_document(id),   -- reversed at most once
  customer_id              TEXT REFERENCES customer(id),
  supplier_id              TEXT REFERENCES supplier(id),
  booking_id               TEXT REFERENCES booking(id),
  cancellation_request_id  TEXT REFERENCES cancellation_request(id),
  money_account_id         TEXT REFERENCES money_account(id),
  payment_method           TEXT CHECK (payment_method IN ('CASH','BANK_TRANSFER','CARD','CHEQUE','WALLET','OTHER')),
  payment_reference        TEXT,
  currency_code            TEXT NOT NULL REFERENCES currency(code),
  exchange_rate            TEXT NOT NULL,             -- to base, frozen; '1' when currency = base
  total_minor              INTEGER NOT NULL CHECK (total_minor > 0),      -- never negative
  total_base_minor         INTEGER NOT NULL CHECK (total_base_minor >= 0),
  reason_code              TEXT,
  description              TEXT,
  created_at               TEXT NOT NULL,
  created_by               TEXT NOT NULL REFERENCES app_user(id),
  CHECK ((is_reversal = 1) = (reversal_of_id IS NOT NULL)),
  CHECK (doc_type NOT LIKE 'CUSTOMER_%' OR customer_id IS NOT NULL),
  CHECK (doc_type NOT LIKE 'SUPPLIER_%' OR supplier_id IS NOT NULL),
  CHECK (doc_type NOT IN ('CUSTOMER_RECEIPT','CUSTOMER_REFUND','SUPPLIER_PAYMENT','SUPPLIER_REFUND','EXPENSE')
         OR (money_account_id IS NOT NULL AND payment_method IS NOT NULL))
) STRICT;
CREATE INDEX ix_doc_date_type ON fin_document(doc_date, doc_type);
CREATE INDEX ix_doc_customer ON fin_document(customer_id, doc_date);
CREATE INDEX ix_doc_supplier ON fin_document(supplier_id, doc_date);
CREATE INDEX ix_doc_booking ON fin_document(booking_id);

CREATE TABLE fin_document_line (
  id                   TEXT PRIMARY KEY,
  document_id          TEXT NOT NULL REFERENCES fin_document(id),
  line_no              INTEGER NOT NULL CHECK (line_no >= 1),
  line_type            TEXT NOT NULL CHECK (line_type IN (
                         'FARE','TAXES','SERVICE_FEE','CHANGE_FEE','CANCELLATION_FEE','DISCOUNT',
                         'SALE_RETURN','PURCHASE_COST','PURCHASE_RETURN','SUPPLIER_PENALTY',
                         'SETTLEMENT','EXPENSE','TRANSFER','APPLICATION','OPENING','FX')),
  booking_id           TEXT REFERENCES booking(id),
  passenger_id         TEXT REFERENCES booking_passenger(id),
  ticket_id            TEXT REFERENCES ticket(id),
  expense_category_id  TEXT REFERENCES expense_category(id),
  description          TEXT,
  amount_minor         INTEGER NOT NULL CHECK (amount_minor > 0),  -- sign comes from doc_type, never from amount
  base_amount_minor    INTEGER NOT NULL CHECK (base_amount_minor >= 0),
  UNIQUE (document_id, line_no)
) STRICT;
CREATE INDEX ix_doc_line_booking ON fin_document_line(booking_id);
CREATE INDEX ix_doc_line_ticket ON fin_document_line(ticket_id);

CREATE TABLE journal_entry (
  id           TEXT PRIMARY KEY,
  document_id  TEXT NOT NULL UNIQUE REFERENCES fin_document(id),
  entry_date   TEXT NOT NULL,
  is_sealed    INTEGER NOT NULL DEFAULT 0 CHECK (is_sealed IN (0,1)),
  created_at   TEXT NOT NULL
) STRICT;
CREATE INDEX ix_journal_entry_date ON journal_entry(entry_date);

CREATE TABLE journal_line (
  id                   TEXT PRIMARY KEY,
  entry_id             TEXT NOT NULL REFERENCES journal_entry(id),
  line_no              INTEGER NOT NULL CHECK (line_no >= 1),
  account_code         TEXT NOT NULL REFERENCES ledger_account(code),
  -- analytical dimensions
  customer_id          TEXT REFERENCES customer(id),
  supplier_id          TEXT REFERENCES supplier(id),
  money_account_id     TEXT REFERENCES money_account(id),
  booking_id           TEXT REFERENCES booking(id),      -- open-item bucket for AR/AP; NULL = on account
  ticket_id            TEXT REFERENCES ticket(id),
  expense_category_id  TEXT REFERENCES expense_category(id),
  -- amounts
  currency_code        TEXT NOT NULL REFERENCES currency(code),
  debit_minor          INTEGER NOT NULL DEFAULT 0 CHECK (debit_minor >= 0),       -- line currency
  credit_minor         INTEGER NOT NULL DEFAULT 0 CHECK (credit_minor >= 0),
  debit_base_minor     INTEGER NOT NULL DEFAULT 0 CHECK (debit_base_minor >= 0),  -- base currency
  credit_base_minor    INTEGER NOT NULL DEFAULT 0 CHECK (credit_base_minor >= 0),
  UNIQUE (entry_id, line_no),
  CHECK (debit_minor = 0 OR credit_minor = 0),
  CHECK (debit_base_minor = 0 OR credit_base_minor = 0),
  CHECK (debit_minor + credit_minor + debit_base_minor + credit_base_minor > 0)
) STRICT;
CREATE INDEX ix_jl_account ON journal_line(account_code);
CREATE INDEX ix_jl_customer ON journal_line(customer_id, account_code) WHERE customer_id IS NOT NULL;
CREATE INDEX ix_jl_supplier ON journal_line(supplier_id, account_code) WHERE supplier_id IS NOT NULL;
CREATE INDEX ix_jl_booking ON journal_line(booking_id) WHERE booking_id IS NOT NULL;
CREATE INDEX ix_jl_money ON journal_line(money_account_id) WHERE money_account_id IS NOT NULL;

-- -----------------------------------------------------------------------------
-- 8. Flight schedule changes & notifications
-- -----------------------------------------------------------------------------
CREATE TABLE schedule_change (
  id                      TEXT PRIMARY KEY,
  booking_id              TEXT NOT NULL REFERENCES booking(id),
  segment_id              TEXT NOT NULL REFERENCES flight_segment(id),
  segment_version_before  INTEGER NOT NULL,
  segment_version_after   INTEGER NOT NULL CHECK (segment_version_after = segment_version_before + 1),
  source                  TEXT NOT NULL DEFAULT 'MANUAL' CHECK (source IN ('MANUAL','AIRLINE_NOTICE','IMPORT')),
  severity                TEXT NOT NULL CHECK (severity IN ('MINOR','MAJOR')),
  before_json             TEXT NOT NULL CHECK (json_valid(before_json)),
  after_json              TEXT NOT NULL CHECK (json_valid(after_json)),
  changed_at              TEXT NOT NULL,
  changed_by              TEXT NOT NULL REFERENCES app_user(id),
  notification_status     TEXT NOT NULL DEFAULT 'NOT_NOTIFIED' CHECK (notification_status IN
                            ('NOT_NOTIFIED','CUSTOMER_NOTIFIED','NOTIFICATION_FAILED','MANUALLY_CONFIRMED')),
  status_updated_at       TEXT,
  status_updated_by       TEXT REFERENCES app_user(id),
  confirmation_note       TEXT,
  customer_response       TEXT CHECK (customer_response IN ('ACCEPTED','REQUESTED_CHANGE','REQUESTED_REFUND')),
  superseded_by_id        TEXT REFERENCES schedule_change(id),
  row_version             INTEGER NOT NULL DEFAULT 1,
  UNIQUE (segment_id, segment_version_after)
) STRICT;
CREATE INDEX ix_schedule_change_attention ON schedule_change(notification_status, changed_at);

CREATE TABLE schedule_change_field (
  change_id   TEXT NOT NULL REFERENCES schedule_change(id),
  field_name  TEXT NOT NULL CHECK (field_name IN (
                'departure_date','departure_time','arrival_date','arrival_time','flight_number',
                'origin_iata','destination_iata','marketing_airline_id','operating_airline_id',
                'departure_terminal','arrival_terminal','cabin_class','status')),
  old_value   TEXT,
  new_value   TEXT,
  PRIMARY KEY (change_id, field_name)
) STRICT;

CREATE TABLE message_template (
  id         TEXT PRIMARY KEY,
  code       TEXT NOT NULL,                 -- 'SCHEDULE_CHANGE', 'PAYMENT_RECEIPT', ...
  channel    TEXT NOT NULL CHECK (channel IN ('WHATSAPP','SMS','EMAIL')),
  locale     TEXT NOT NULL CHECK (locale IN ('ar','en')),
  subject    TEXT,
  body       TEXT NOT NULL,                 -- {{placeholders}} rendered by code
  is_active  INTEGER NOT NULL DEFAULT 1 CHECK (is_active IN (0,1)),
  updated_at TEXT NOT NULL,
  UNIQUE (code, channel, locale)
) STRICT;

CREATE TABLE notification (
  id                   TEXT PRIMARY KEY,
  channel              TEXT NOT NULL CHECK (channel IN ('WHATSAPP','SMS','EMAIL','PHONE_CALL')),
  delivery_mode        TEXT NOT NULL CHECK (delivery_mode IN ('MANUAL','PROVIDER')),
  provider             TEXT,                -- NULL for MANUAL
  template_code        TEXT,
  recipient_address    TEXT NOT NULL,       -- E.164 or e-mail, snapshot
  recipient_name       TEXT,
  customer_id          TEXT REFERENCES customer(id),
  booking_id           TEXT REFERENCES booking(id),
  schedule_change_id   TEXT REFERENCES schedule_change(id),
  subject              TEXT,
  body                 TEXT NOT NULL,       -- exact text sent (snapshot)
  status               TEXT NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING','SENT','DELIVERED','FAILED','CANCELLED')),
  provider_message_id  TEXT,
  error_message        TEXT,
  attempt_count        INTEGER NOT NULL DEFAULT 0,
  created_at           TEXT NOT NULL,
  created_by           TEXT NOT NULL REFERENCES app_user(id),
  sent_at              TEXT,
  sent_by              TEXT REFERENCES app_user(id),
  status_updated_at    TEXT
) STRICT;
CREATE INDEX ix_notification_booking ON notification(booking_id);
CREATE INDEX ix_notification_change ON notification(schedule_change_id);

-- -----------------------------------------------------------------------------
-- 9. Audit, backups, search
-- -----------------------------------------------------------------------------
CREATE TABLE audit_log (
  seq            INTEGER PRIMARY KEY AUTOINCREMENT,   -- total order for the hash chain
  id             TEXT NOT NULL UNIQUE,
  occurred_at    TEXT NOT NULL,
  user_id        TEXT REFERENCES app_user(id),        -- NULL only for SYSTEM actions
  session_id     TEXT REFERENCES user_session(id),
  workstation    TEXT,
  action         TEXT NOT NULL,                       -- 'booking.issue', 'auth.login_failed', ...
  entity_type    TEXT NOT NULL,
  entity_id      TEXT,
  before_json    TEXT CHECK (before_json IS NULL OR json_valid(before_json)),
  after_json     TEXT CHECK (after_json IS NULL OR json_valid(after_json)),
  metadata_json  TEXT CHECK (metadata_json IS NULL OR json_valid(metadata_json)),
  prev_hash      TEXT NOT NULL,
  hash           TEXT NOT NULL                        -- sha256(prev_hash || canonical(row))
) STRICT;
CREATE INDEX ix_audit_entity ON audit_log(entity_type, entity_id);
CREATE INDEX ix_audit_user_time ON audit_log(user_id, occurred_at);

CREATE TABLE backup_record (
  id               TEXT PRIMARY KEY,
  kind             TEXT NOT NULL CHECK (kind IN ('MANUAL','SCHEDULED','ON_EXIT','PRE_MIGRATION','PRE_RESTORE')),
  started_at       TEXT NOT NULL,
  finished_at      TEXT,
  status           TEXT NOT NULL CHECK (status IN ('RUNNING','SUCCEEDED','FAILED')),
  file_path        TEXT,
  file_size_bytes  INTEGER,
  sha256           TEXT,
  schema_version   INTEGER NOT NULL,
  app_version      TEXT NOT NULL,
  is_encrypted     INTEGER NOT NULL CHECK (is_encrypted IN (0,1)),
  verified_at      TEXT,
  error_message    TEXT,
  created_by       TEXT REFERENCES app_user(id)
) STRICT;

-- Single global search index maintained by the application in the same
-- transaction as the source write. Text is pre-normalised (Arabic letter
-- folding, digits to ASCII, phone digits) before insert AND before query.
CREATE VIRTUAL TABLE search_index USING fts5(
  entity_type UNINDEXED,
  entity_id   UNINDEXED,
  content,
  tokenize = 'trigram remove_diacritics 1'
);

-- -----------------------------------------------------------------------------
-- 10. Integrity triggers (defence in depth; the service layer enforces first)
-- -----------------------------------------------------------------------------
CREATE TRIGGER trg_fin_document_no_update BEFORE UPDATE ON fin_document
BEGIN SELECT RAISE(ABORT, 'fin_document is immutable; post a reversal or adjustment'); END;
CREATE TRIGGER trg_fin_document_no_delete BEFORE DELETE ON fin_document
BEGIN SELECT RAISE(ABORT, 'fin_document cannot be deleted'); END;

CREATE TRIGGER trg_fin_document_line_no_update BEFORE UPDATE ON fin_document_line
BEGIN SELECT RAISE(ABORT, 'fin_document_line is immutable'); END;
CREATE TRIGGER trg_fin_document_line_no_delete BEFORE DELETE ON fin_document_line
BEGIN SELECT RAISE(ABORT, 'fin_document_line cannot be deleted'); END;

-- Period lock: nothing may be dated on/before the lock date.
CREATE TRIGGER trg_fin_document_lock_date BEFORE INSERT ON fin_document
WHEN NEW.doc_date <= COALESCE((SELECT financial_lock_date FROM company_profile WHERE id = 1), '0000-00-00')
BEGIN SELECT RAISE(ABORT, 'document date falls in a locked financial period'); END;

-- A reversal must mirror the original's type, party and amount.
CREATE TRIGGER trg_fin_document_reversal_shape BEFORE INSERT ON fin_document
WHEN NEW.is_reversal = 1 AND NOT EXISTS (
  SELECT 1 FROM fin_document o
  WHERE o.id = NEW.reversal_of_id AND o.is_reversal = 0
    AND o.doc_type = NEW.doc_type AND o.total_minor = NEW.total_minor
    AND o.currency_code = NEW.currency_code
    AND o.customer_id IS NEW.customer_id AND o.supplier_id IS NEW.supplier_id)
BEGIN SELECT RAISE(ABORT, 'reversal does not mirror its original document'); END;

CREATE TRIGGER trg_journal_line_no_update BEFORE UPDATE ON journal_line
BEGIN SELECT RAISE(ABORT, 'journal_line is immutable'); END;
CREATE TRIGGER trg_journal_line_no_delete BEFORE DELETE ON journal_line
BEGIN SELECT RAISE(ABORT, 'journal_line cannot be deleted'); END;
CREATE TRIGGER trg_journal_line_sealed BEFORE INSERT ON journal_line
WHEN (SELECT is_sealed FROM journal_entry WHERE id = NEW.entry_id) = 1
BEGIN SELECT RAISE(ABORT, 'journal_entry is sealed'); END;

-- The only permitted UPDATE on journal_entry is sealing, and only if balanced.
CREATE TRIGGER trg_journal_entry_seal BEFORE UPDATE ON journal_entry
BEGIN
  SELECT RAISE(ABORT, 'journal_entry is immutable')
   WHERE NOT (OLD.is_sealed = 0 AND NEW.is_sealed = 1
              AND NEW.id = OLD.id AND NEW.document_id = OLD.document_id
              AND NEW.entry_date = OLD.entry_date AND NEW.created_at = OLD.created_at);
  SELECT RAISE(ABORT, 'journal_entry is unbalanced or has fewer than 2 lines')
   WHERE (SELECT COUNT(*) FROM journal_line WHERE entry_id = NEW.id) < 2
      OR (SELECT SUM(debit_base_minor) - SUM(credit_base_minor) FROM journal_line WHERE entry_id = NEW.id) <> 0;
END;
CREATE TRIGGER trg_journal_entry_no_delete BEFORE DELETE ON journal_entry
BEGIN SELECT RAISE(ABORT, 'journal_entry cannot be deleted'); END;

CREATE TRIGGER trg_audit_no_update BEFORE UPDATE ON audit_log
BEGIN SELECT RAISE(ABORT, 'audit_log is append-only'); END;
CREATE TRIGGER trg_audit_no_delete BEFORE DELETE ON audit_log
BEGIN SELECT RAISE(ABORT, 'audit_log is append-only'); END;

-- Base currency is frozen once anything has been posted.
CREATE TRIGGER trg_company_base_currency_frozen BEFORE UPDATE OF base_currency_code ON company_profile
WHEN NEW.base_currency_code <> OLD.base_currency_code AND EXISTS (SELECT 1 FROM journal_entry)
BEGIN SELECT RAISE(ABORT, 'base currency cannot change after financial postings exist'); END;

-- The lock date can only move backwards (unlock) through a dedicated audited command;
-- this trigger just forbids clearing it silently to NULL.
CREATE TRIGGER trg_company_lock_date_not_null BEFORE UPDATE OF financial_lock_date ON company_profile
WHEN OLD.financial_lock_date IS NOT NULL AND NEW.financial_lock_date IS NULL
BEGIN SELECT RAISE(ABORT, 'lock date cannot be cleared; move it explicitly'); END;

-- Financial history must never be orphaned.
CREATE TRIGGER trg_booking_no_delete BEFORE DELETE ON booking
WHEN OLD.status NOT IN ('DRAFT','DISCARDED') OR EXISTS (SELECT 1 FROM fin_document WHERE booking_id = OLD.id)
BEGIN SELECT RAISE(ABORT, 'booking with financial history cannot be deleted'); END;
CREATE TRIGGER trg_customer_no_delete BEFORE DELETE ON customer
BEGIN SELECT RAISE(ABORT, 'customers are deactivated, never deleted'); END;
CREATE TRIGGER trg_supplier_no_delete BEFORE DELETE ON supplier
BEGIN SELECT RAISE(ABORT, 'suppliers are deactivated, never deleted'); END;

-- -----------------------------------------------------------------------------
-- 11. Read models (views). Base-currency figures. All derived from the journal,
--     never from mutable columns. See 04-financial-model.md §8 for definitions.
-- -----------------------------------------------------------------------------
CREATE VIEW v_journal AS
SELECT jl.*, je.entry_date, d.doc_type, d.is_reversal, d.doc_no, la.account_class
FROM journal_line jl
JOIN journal_entry je ON je.id = jl.entry_id
JOIN fin_document d   ON d.id = je.document_id
JOIN ledger_account la ON la.code = jl.account_code;

CREATE VIEW v_booking_financials AS
SELECT
  b.id AS booking_id,
  b.booking_no,
  b.customer_id,
  COALESCE(SUM(CASE WHEN j.account_class IN ('REVENUE','CONTRA_REVENUE')
                    THEN j.credit_base_minor - j.debit_base_minor END), 0)            AS net_sales_base_minor,
  COALESCE(SUM(CASE WHEN j.account_class IN ('COST','CONTRA_COST')
                    THEN j.debit_base_minor - j.credit_base_minor END), 0)            AS net_cost_base_minor,
  -- Gross profit = net sales - net cost. Cash accounts are never part of this.
  COALESCE(SUM(CASE WHEN j.account_class IN ('REVENUE','CONTRA_REVENUE','COST','CONTRA_COST')
                    THEN j.credit_base_minor - j.debit_base_minor END), 0)            AS gross_profit_base_minor,
  COALESCE(SUM(CASE WHEN j.account_code = '1200' AND j.doc_type IN
                      ('CUSTOMER_RECEIPT','CUSTOMER_REFUND','BALANCE_APPLICATION')
                    THEN j.credit_base_minor - j.debit_base_minor END), 0)            AS customer_paid_net_base_minor,
  COALESCE(SUM(CASE WHEN j.account_code = '1200'
                    THEN j.debit_base_minor - j.credit_base_minor END), 0)            AS customer_balance_base_minor,
  COALESCE(SUM(CASE WHEN j.account_code = '2100' AND j.doc_type IN
                      ('SUPPLIER_PAYMENT','SUPPLIER_REFUND','BALANCE_APPLICATION')
                    THEN j.debit_base_minor - j.credit_base_minor END), 0)            AS supplier_paid_net_base_minor,
  COALESCE(SUM(CASE WHEN j.account_code = '2100'
                    THEN j.credit_base_minor - j.debit_base_minor END), 0)            AS supplier_balance_base_minor
FROM booking b
LEFT JOIN v_journal j ON j.booking_id = b.id
GROUP BY b.id;

CREATE VIEW v_customer_balance AS
SELECT customer_id, currency_code,
       SUM(debit_minor - credit_minor)           AS balance_minor,       -- >0 customer owes us
       SUM(debit_base_minor - credit_base_minor) AS balance_base_minor
FROM journal_line WHERE account_code = '1200'
GROUP BY customer_id, currency_code;

CREATE VIEW v_supplier_balance AS
SELECT supplier_id, currency_code,
       SUM(credit_minor - debit_minor)           AS balance_minor,       -- >0 we owe supplier
       SUM(credit_base_minor - debit_base_minor) AS balance_base_minor
FROM journal_line WHERE account_code = '2100'
GROUP BY supplier_id, currency_code;

CREATE VIEW v_money_account_balance AS
SELECT money_account_id, currency_code,
       SUM(debit_minor - credit_minor) AS balance_minor
FROM journal_line WHERE account_code = '1110'
GROUP BY money_account_id, currency_code;

-- -----------------------------------------------------------------------------
-- 12. Seed: system chart of accounts (codes are referenced by posting rules)
-- -----------------------------------------------------------------------------
INSERT INTO ledger_account (code, name_ar, name_en, account_class, normal_side, dimension) VALUES
 ('1110','النقدية والبنوك','Cash & bank','ASSET','DEBIT','MONEY_ACCOUNT'),
 ('1200','ذمم العملاء','Accounts receivable – customers','ASSET','DEBIT','CUSTOMER'),
 ('2100','ذمم الموردين','Accounts payable – suppliers','LIABILITY','CREDIT','SUPPLIER'),
 ('3100','أرصدة افتتاحية','Opening balance equity','EQUITY','CREDIT','NONE'),
 ('3200','جاري المالك','Owner capital & drawings','EQUITY','CREDIT','NONE'),
 ('4100','مبيعات التذاكر','Ticket sales','REVENUE','CREDIT','NONE'),
 ('4110','مردودات وإلغاءات المبيعات','Sales returns & cancellations','CONTRA_REVENUE','DEBIT','NONE'),
 ('4120','خصومات مسموح بها','Discounts allowed','CONTRA_REVENUE','DEBIT','NONE'),
 ('4200','رسوم خدمة وتعديل','Service & change fees','REVENUE','CREDIT','NONE'),
 ('4210','رسوم إلغاء','Cancellation fees','REVENUE','CREDIT','NONE'),
 ('5100','تكلفة التذاكر','Ticket purchase cost','COST','DEBIT','NONE'),
 ('5110','مردودات المشتريات','Purchase returns (supplier credits)','CONTRA_COST','CREDIT','NONE'),
 ('5200','غرامات ورسوم الموردين','Supplier penalties & charges','COST','DEBIT','NONE'),
 ('6110','إيجار','Rent','EXPENSE','DEBIT','NONE'),
 ('6120','رواتب','Salaries','EXPENSE','DEBIT','NONE'),
 ('6130','إنترنت واتصالات','Internet & telecom','EXPENSE','DEBIT','NONE'),
 ('6140','كهرباء ومرافق','Electricity & utilities','EXPENSE','DEBIT','NONE'),
 ('6150','رسوم بنكية','Bank charges','EXPENSE','DEBIT','NONE'),
 ('6160','مصروفات مكتبية','Office expenses','EXPENSE','DEBIT','NONE'),
 ('6170','انتقالات','Transportation','EXPENSE','DEBIT','NONE'),
 ('6190','مصروفات تشغيل أخرى','Other operating expenses','EXPENSE','DEBIT','NONE'),
 ('7100','فروق عملة محققة','Realised FX gain/loss','OTHER','CREDIT','NONE'),
 ('7200','فروق تقريب','Rounding differences','OTHER','CREDIT','NONE');
